### ISSUE TITLE
fix the below issue

### ISSUE THREAD

**Issue by rvsp** [sourabhrajwade/Razorpay-checkout#1]
https://github.com/sourabhrajwade/Razorpay-checkout/blob/beeba43b48b6acb5975b688ee83f6f52ab52f366/src/app/header/header.component.ts#L20

![image](https://user-images.githubusercontent.com/21954626/84123644-ba23b380-aa57-11ea-8d11-166516b3b186.png)

**Comment by sourabhrajwade** [comment]
You might be getting error as I have removed the my secret key. Please enter your key in the place to make it work. Its not bug, I intentionally did it. 

Thanks for review.
